### ISSUE TITLE
Retail churn analytics data source is incorrect

### ISSUE THREAD

**Issue by piersbatch** [Snowflake-Labs/snowpark-python-demos#1]
The datasource specified does not contain the fields mentioned in the code

CREATE OR REPLACE EXTERNAL TABLE SRC_CUSTOMER 
(CUSTOMER_ID VARCHAR(40) as (value:c1::varchar), 
 CREATED_DT DATE as (value:c2::date), 
 CITY VARCHAR(40) as (value:c3::varchar), 
 STATE VARCHAR(2) as (value:c4::varchar), 
 FAV_DELIVERY_DAY VARCHAR(40) as (value:c5::varchar), 
 REFILL  NUMBER(38,0) as (value:c6::integer), 
 DOOR_DELIVERY  NUMBER(38,0) as (value:c7::integer), 
 PAPERLESS  NUMBER(38,0) as (value:c8::integer), 
 CUSTOMER_NAME VARCHAR(40) as (value:c9::varchar),  
 RETAINED  NUMBER(38,0) as (value:c10::integer) 
) 

> These datasets were generated for this demo using a Kaggle dataset below.
> 
> Reference: https://www.kaggle.com/uttamp/store-data

**Comment by iamontheinet** [comment]
Hi @piersbatch! Thanks for reporting the issue. We're looking into fixing it and will provide an update when it's resolved.

**Comment by sfc-gh-ejohnson** [comment]
Hi @piersbatch .  Could you pls confirm that you uploaded the 3 CSV files in /data into an external stage (e.g  <my_bucket>) and created 3 directories /customer, /order, /comm_hist in your bucket and uploaded the source files src_customer.csv, src_order.csv, src_comm_hist.csv respectively into each of these 3 directories.

CREATE STAGE CHURN_SOURCE_DATA 
storage_integration = <your_storage_integration>
  url = 's3://<your bucket>'
  file_format = (type=CSV);

The SRC_CUSTOMER external table definition specifies   LOCATION = **@churn_source_data/customer/**   .

Thanks!

**Comment by iamontheinet** [comment]
@piersbatch Please confirm if the above solution works for you or not. Thanks!
