### ISSUE TITLE
Readme setup instructions `conda`

### ISSUE THREAD

**Issue by samadarshad** [Snowflake-Labs/snowpark-python-demos#10]
For https://github.com/Snowflake-Labs/snowpark-python-demos/tree/main/Advertising-Spend-ROI-Prediction
Setup instructions says use `pip install conda` then run `conda ...` but get following error:

```
conda
ERROR: The install method you used for conda--probably either `pip install conda`
or `easy_install conda`--is not compatible with using conda as an application.
If your intention is to install conda as a standalone application, currently
supported install methods include the Anaconda installer and the miniconda
installer.  You can download the miniconda installer from
https://conda.io/miniconda.html.
```

Therefore should update the instructions to remove `pip install conda` and install via miniconda instead

**Comment by iamontheinet** [comment]
Thanks @samadarshad! I've updated the instructions in README.
