### ISSUE TITLE
batch_predict_roi UDF input type error

### ISSUE THREAD

**Issue by mrecos** [Snowflake-Labs/snowpark-python-demos#11]
Hello All,
In the `Snowpark_For_Python.ipynb` demo, the `batch_predict_roi` UDF returns the error below. I assume this is because of the 
expectation of a pandas df in the function:
`def batch_predict_roi(budget_allocations_df: PandasDataFrame[int, int, int, int]) -> PandasSeries[float]:`
but instead, it gets an array. Any help in clearing this up would be appreciated.

https://github.com/Snowflake-Labs/snowpark-python-demos/blob/main/Advertising-Spend-ROI-Prediction/Snowpark_For_Python.ipynb

`Failed to execute query [queryID: 01a80045-0004-3087-002b-9e87000e507e]  SELECT "SEARCH_ENGINE", "SOCIAL_MEDIA", "VIDEO", "EMAIL", batch_predict_roi(array_construct("SEARCH_ENGINE", "SOCIAL_MEDIA", "VIDEO", "EMAIL")) AS "PREDICTED_ROI" FROM ( SELECT  *  FROM ( VALUES (250000 :: INT, 250000 :: INT, 200000 :: INT, 450000 :: INT), (500000 :: INT, 500000 :: INT, 500000 :: INT, 500000 :: INT), (8500 :: INT, 9500 :: INT, 2000 :: INT, 500 :: INT) AS SNOWPARK_TEMP_TABLE_H7ZD6LZPZ4("SEARCH_ENGINE", "SOCIAL_MEDIA", "VIDEO", "EMAIL"))) LIMIT 10
001044 (42P13): SQL compilation error: error line 1 at position 58
Invalid argument types for function 'BATCH_PREDICT_ROI': (ARRAY)`

**Comment by iamontheinet** [comment]
@mrecos Thanks! I am looking into this issue and will post an update as soon as it's resolved.

**Comment by iamontheinet** [comment]
@mrecos I've pushed the updates. Can you please try it again and see it it works for you? Thanks!
