### ISSUE TITLE
No Loading of Data in External table

### ISSUE THREAD

**Issue by Navedya06** [Snowflake-Labs/snowpark-python-demos#7]
For the retail-churn-analytics demo
The data doesn't get copied from the S3 bucket to the external tables created.

CREATE OR REPLACE EXTERNAL TABLE SRC_CUSTOMER 
(CUSTOMER_ID VARCHAR(40) as (value:c1::varchar), 
 CREATED_DT DATE as (value:c2::date), 
 CITY VARCHAR(40) as (value:c3::varchar), 
 STATE VARCHAR(2) as (value:c4::varchar), 
 FAV_DELIVERY_DAY VARCHAR(40) as (value:c5::varchar), 
 REFILL  NUMBER(38,0) as (value:c6::integer), 
 DOOR_DELIVERY  NUMBER(38,0) as (value:c7::integer), 
 PAPERLESS  NUMBER(38,0) as (value:c8::integer), 
 CUSTOMER_NAME VARCHAR(40) as (value:c9::varchar),  
 RETAINED  NUMBER(38,0) as (value:c10::integer) 
) 
  LOCATION = @churn_source_data/customer/ 
  REFRESH_ON_CREATE = TRUE 
  AUTO_REFRESH = TRUE 
  FILE_FORMAT = ( TYPE = CSV SKIP_HEADER=1);

This is the exact syntax I have used.
@iamontheinet - please guide me on the same

**Comment by iamontheinet** [comment]
Hi @Navedya06! Thanks for reporting the issue. We're looking into fixing it and will provide an update when it's resolved.

**Comment by sfc-gh-ejohnson** [comment]
Hi @Navedya06 . Thank you for reporting this. Could you please confirm that your src_customer.csv is in /customer directory in your object store as it is referenced in the external table definition?

LOCATION = @churn_source_data/customer/

Thank you.

**Comment by Navedya06** [comment]
@sfc-gh-ejohnson Thank you, I have made the necessary corrections.
