### ISSUE TITLE
Execution failure

### ISSUE THREAD

**Issue by Navedya06** [Snowflake-Labs/snowpark-python-demos#8]
<img width="428" alt="image" src="https://user-images.githubusercontent.com/68197201/181081108-827b6501-f0e2-46f1-bc18-932637534c80.png">

Got a Python Interpreter Error-
@sfc-gh-ejohnson Please help with the same.

Thank you!

**Comment by sfc-gh-ejohnson** [comment]
Hi @Navedya06 . Have you installed snowpark python in your local environment as stated in the README? (I also just added the link)
https://docs.snowflake.com/en/developer-guide/snowpark/python/setup.html#installation-instructions
Also please make sure the cell above with 
**session.add_packages('snowflake-snowpark-python')**

also got executed before you run this cell. add_packages() makes sure that snowpark is pulled as a dependency when running the Python SP on the server side. 

Please let me know if these two steps help. 

Thanks!

**Comment by Navedya06** [comment]
![image](https://user-images.githubusercontent.com/68197201/181155965-d3d809cd-212f-4252-8cf6-d1b6c8be42ad.png)

The table_name variable is not declared
Can you tell me the value for the same please?


Thank you!
